version: '3.11.9'

services:
  api:
    image: tomherbet/credit-risk-api:latest
    ports:
      - "8000:8000"
    volumes:
      # ModÃ¨le : Racine VPS -> Racine App
      - ./best_lgbm_model.pkl:/app/best_lgbm_model.pkl
      
      # Train : Racine VPS -> Racine App
      - ./application_train.csv:/app/application_train.csv
      
      # Test : Racine VPS -> Racine App
      - ./application_test.csv:/app/application_test.csv
    environment:
      - MODEL_PATH=/app/best_lgbm_model.pkl
      - DATA_DIR=/app/data
    restart: unless-stopped