version: '3.11.9'

services:
  api:
    image: tomherbet/credit-risk-api:latest
    ports:
      - "8000:8000"
    volumes:
      - /home/deploy/app/best_lgbm_model.pkl:/app/best_lgbm_model.pkl:ro
      - /home/deploy/app/data:/app/data:ro
    environment:
      - MODEL_PATH=/app/best_lgbm_model.pkl
      - DATA_DIR=/app/data
    restart: unless-stopped